# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample-cloud
spec:
  parallelism: 5
  arguments: --out cloud
  script:
    configMap:
      name: k6-demo-configmap-cloud
      file: single_request_complete_script.js


      
