# k6-resource.yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: k6-test
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-demo-configmap
      file: multiple_requests.js
  arguments: k6 run multiple_requests.js
