# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: k6-sample
spec:
  parallelism: 4
  script:
    configMap:
      name: k6-demo-configmap
      file: multiple_requests.js
  arguments: k6 run multiple_requests.js
