# k6-resource.yml

apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: k6-sample-loadtest
spec:
  parallelism: 6
  script:
    configMap:
      name: k6-demo-configmap-soaktest
      file: multiple_requests_complete_script.js


      
