apiVersion: v1
kind: ConfigMap
metadata:
  name: nr-map
data:
  nri-statsd.toml: |
    backends='newrelic'
    flush-interval='10s'
    statser-type='null'
    log-raw-metric='true'

    [newrelic]
    # flush types supported: metrics,  insights, infra
    flush-type = 'metrics'
    transport = 'default'
    # newrelic event address
    address = "https://collector.newrelic.com/v1/accounts/<enter your newrelic account id>/events"
    # newrelic metric api address
    address-metrics = "https://metric-api.newrelic.com/metric/v1"
    api-key = 'enter your newrelic api key'
