apiVersion: v1
kind: Service
metadata:
  name: newrelic-statsd-svc
  labels:
    app: newrelic-statsd
spec:
  type: ClusterIP
  ports:
  - name: newrelic-statsd
    port: 80
    targetPort: 8125
    protocol: UDP
  selector:
    app: newrelic-statsd