apiVersion: apps/v1
kind: Deployment
metadata:
  name: newrelic-statsd
  labels:
    app: newrelic-statsd
spec:
  selector:
    matchLabels:
      app: newrelic-statsd
  replicas: 1
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: newrelic-statsd
    spec:
      volumes:
        - name: newrelic-vol
          configMap:
            name: nr-map
      containers:
      - name: newrelic-statsd
        image: newrelic/nri-statsd:latest
        ports:
        - containerPort: 8125
        volumeMounts:
          - name: newrelic-vol
            mountPath: /etc/opt/newrelic
        env:
        - name: NR_ACCOUNT_ID
          value: "4186793"
        - name: NR_API_KEY
          value: "d7080dcff62804a546c1260125818f777002NRAL"
        - name: NR_LOG_METRICS
          value: "true"